// Emits build/embedded_assets.hpp: the bridge executable and extension files as byte arrays so
// HypeTabs.exe can unpack them itself. Built from build/ outputs; no packages are used.
import { readFile, writeFile } from 'node:fs/promises';
const root = new URL('../build/', import.meta.url);
const assets = [
    ['HypeTabs.Bridge.exe', 'bridge_exe'],
    ['extension/manifest.json', 'extension_manifest'],
    ['extension/worker.js', 'extension_worker'],
];
let out = '#pragma once\n// Generated by tools/embed-assets.mjs; do not edit.\n#include <cstddef>\nnamespace hype::embedded {\n';
for (const [file, name] of assets) {
    const bytes = await readFile(new URL(file, root));
    out += `inline constexpr unsigned char ${name}[] = {`;
    for (let i = 0; i < bytes.length; ++i) out += (i % 40 ? '' : '\n') + bytes[i] + ',';
    out += `};\ninline constexpr size_t ${name}_size = ${bytes.length};\n`;
}
out += '}\n';
await writeFile(new URL('embedded_assets.hpp', root), out);
console.log(`Embedded ${assets.length} assets into build/embedded_assets.hpp.`);
